# Generated by Django 3.1 on 2025-08-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20250806_2216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariationModel',
            new_name='Variation',
        ),
    ]
